# Generated by Django 3.0.14 on 2021-05-12 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follower_set',
            field=models.ManyToManyField(blank=True, related_name='my_following_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='following_set',
            field=models.ManyToManyField(blank=True, related_name='my_follower_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
